steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/servian-tech/goapp-image', '.']
- name: 'gcr.io/cloud-builders/docker'  
  args: ['push', 'gcr.io/servian-tech/goapp-image']
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']