steps:
- name: 'hashicorp/terraform:0.12.26'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform
      terraform init
      cd ..
- name: 'hashicorp/terraform:0.12.26'
  env:
  - 'TF_VAR_project=$PROJECT_ID'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform
      terraform plan -out=plan
      cd ..
- name: 'hashicorp/terraform:0.12.26'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform
      terraform apply plan
      cd ..
  env:
  - 'TF_VAR_project=$PROJECT_ID'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      gcloud container clusters get-credentials example-private-cluster --region=australia-southeast1
  env:
  - 'PROJECT=$PROJECT_ID'
   
- name: 'gcr.io/cloud-builders/gke-deploy'
  entrypoint: 'sh'
  args: ['./cloud-build/gke-deploy.sh']
  env:
  - 'PROJECT=$PROJECT_ID'

timeout: '1200s'